"""Records the co-driver's pace-note vocabulary with the Kokoro neural TTS
(Apache-2.0, https://github.com/thewh1teagle/kokoro-onnx) and packages the
clips as base64 MP3 inside a JS module, so they load anywhere scripts load.

    pip install kokoro-onnx soundfile numpy
    # model files from the kokoro-onnx GitHub release "model-files-v1.0":
    #   kokoro-v1.0.int8.onnx, voices-v1.0.bin   (put them next to this script or pass --models)
    python3 rally/tools/make_voice.py --models /path/to/models

Requires ffmpeg on PATH.
"""
import argparse, base64, json, os, subprocess, tempfile
import numpy as np
import soundfile as sf
from kokoro_onnx import Kokoro

# key -> (text, speed). Keys are what src/codriver.js asks for.
PHRASES = {}
for side in ("left", "right"):
    for sev in ("flat", "easy", "medium", "hard", "square", "hairpin"):
        PHRASES[f"{sev}_{side}"] = (f"{sev.capitalize()} {side}.", 1.3)
PHRASES.update({
    "long": ("long.", 1.3), "very_long": ("very long.", 1.3),
    "tightens": ("tightens.", 1.3), "opens": ("opens.", 1.3),
    "dont_cut": ("don't cut.", 1.3), "keep_in": ("keep in.", 1.3), "keep_out": ("keep out.", 1.3),
    "caution": ("Caution!", 1.25), "over_crest": ("over crest.", 1.3), "jump": ("Jump!", 1.2),
    "big_jump": ("Big jump!", 1.2), "bumps": ("bumps.", 1.3), "into": ("into", 1.35), "and": ("and", 1.35),
    "water_splash": ("water splash.", 1.3), "narrows": ("narrows.", 1.3), "over_bridge": ("over bridge.", 1.3),
    "flat_out": ("flat out.", 1.3), "dip": ("dip.", 1.3), "ruts": ("ruts.", 1.3), "ice": ("ice!", 1.25),
    "d50": ("fifty.", 1.3), "d100": ("one hundred.", 1.3), "d150": ("one fifty.", 1.3), "d200": ("two hundred.", 1.3),
    "d300": ("three hundred.", 1.3), "d400": ("four hundred.", 1.3), "d500": ("five hundred.", 1.3),
    "c5": ("Five.", 1.15), "c4": ("Four.", 1.15), "c3": ("Three.", 1.15), "c2": ("Two.", 1.15), "c1": ("One.", 1.15),
    "go": ("Go! Go! Go!", 1.25),
    "ready": ("Right. Stage start. Good luck.", 1.15),
    "finish": ("Flying finish!", 1.2),
    "split": ("Split.", 1.2),
    "good_stage": ("Brilliant stage! That was brilliant!", 1.15),
    "ok_stage": ("Good. Solid stage, that.", 1.15),
    "slow_stage": ("We lost a bit of time there. Keep pushing.", 1.15),
    "fastest": ("Fastest time! Get in there!", 1.15),
    "nice": ("Nice!", 1.2), "steady": ("Steady, steady.", 1.25), "careful": ("Careful!", 1.25),
    "ouch": ("Ooh. That hurt.", 1.2), "back_on": ("Right, we're back on. Keep going.", 1.2),
    "damage": ("Watch it, the car's taking damage.", 1.2),
    "engine_bad": ("Engine's not sounding good.", 1.2),
    "puncture": ("Puncture!", 1.2), "wrong_way": ("Wrong way! Turn around!", 1.2),
    "halfway": ("Halfway. Keep it tidy.", 1.2),
})

VOICES = {"george": "bm_george", "emma": "bf_emma"}


def trim(audio, sr, thresh=0.012, pad=0.02):
    idx = np.where(np.abs(audio) > thresh)[0]
    if len(idx) == 0:
        return audio
    a = max(0, idx[0] - int(pad * sr)); b = min(len(audio), idx[-1] + int(pad * 2 * sr))
    out = audio[a:b].copy()
    fade = int(0.006 * sr)
    out[:fade] *= np.linspace(0, 1, fade); out[-fade:] *= np.linspace(1, 0, fade)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", default=os.path.dirname(os.path.abspath(__file__)))
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "assets", "voice"))
    args = ap.parse_args()
    k = Kokoro(os.path.join(args.models, "kokoro-v1.0.int8.onnx"), os.path.join(args.models, "voices-v1.0.bin"))
    lang = {"george": "en-gb", "emma": "en-gb"}
    for name, voice in VOICES.items():
        clips = {}
        with tempfile.TemporaryDirectory() as tmp:
            for key, (text, speed) in PHRASES.items():
                audio, sr = k.create(text, voice=voice, speed=speed, lang=lang[name])
                audio = trim(np.asarray(audio, dtype=np.float32), sr)
                peak = np.max(np.abs(audio)) or 1
                audio = audio / peak * 0.89
                wav = os.path.join(tmp, key + ".wav"); mp3 = os.path.join(tmp, key + ".mp3")
                sf.write(wav, audio, sr)
                subprocess.run(["ffmpeg", "-loglevel", "error", "-y", "-i", wav, "-ac", "1", "-b:a", "48k", mp3], check=True)
                clips[key] = base64.b64encode(open(mp3, "rb").read()).decode()
        path = os.path.join(args.out, f"{name}.js")
        with open(path, "w") as f:
            f.write(f"// Co-driver voice '{name}': Kokoro TTS voice {voice} (Apache-2.0), base64 MP3 per pace-note word.\n")
            f.write("// Generated by rally/tools/make_voice.py.\nexport default ")
            json.dump(clips, f, separators=(",", ":"))
            f.write(";\n")
        print(path, os.path.getsize(path) // 1024, "KB", len(clips), "clips")


if __name__ == "__main__":
    main()
